model:
  name: esm2_t6_8M_UR50D
  pretrained: true
  save_dir: /home/anton.thieme/mydata/projects/TabulaSapiens/models/esm/

training:
  epochs: 10
  batch_size: 8
  learning_rate: 0.00002
  k_folds: 5
  optimizer: Adam

data:
  csv_file: /home/anton.thieme/mydata/projects/TabulaSapiens/data/esm/v2/train_data.csv
  shuffle: true
  train_split: 0.8

run:
  run_dir: /home/anton.thieme/mydata/projects/TabulaSapiens/runs