model:
  name: esm2_t12_35M_UR50D
  pretrained: true
  save_dir: /home/anton.thieme/mydata/projects/TabulaSapiens/models/esm/

training:
  epochs: 20
  batch_size: 8
  learning_rate: 0.00002
  k_folds: 5
  optimizer: Adam

data:
  csv_file: /home/anton.thieme/mydata/projects/TabulaSapiens/results/motif/motif_sequence_data.csv
  shuffle: true
  train_split: 0.8

run:
  run_dir: /home/anton.thieme/mydata/projects/TabulaSapiens/runs